# Every entry must be associated with at least one SDK version – corresponding
# to the Dart SDK version or the Flutter framework version, depending on the
# type of package. It can be specified at the top-lever as a single value or
# an array. Alternatively, you can specify the SDK version(s) within each job.
sdk:
  - stable

stages:
  - analyzer_and_format:
      - group:
          - format
          - analyze: --fatal-infos .